us:
  state:
    regions:
      - US-AR
      - US-AZ
      - US-CA
      - US-CO
      - US-CT
      - US-DE
      - US-FL
      - US-GA
      - US-IA
      - US-ID
      - US-IL
      - US-IN
      - US-KS
      - US-KY
      - US-LA
      - US-MA
      - US-MD
      - US-ME
      - US-VT
      - US-MO
      - US-MT
      - US-NC
      - US-ND
      - US-NE
      - US-NH
      - US-NJ
      - US-NM
      - US-NY
      - US-OH
      - US-OK
      - US-OR
      - US-PA
      - US-RI
      - US-SC
      - US-SD
      - US-TN
      - US-TX
      - US-VA
      - US-WA
      - US-WI
      - US-WV
      - US-WY
      - US-AS
      - US-DC
      - US-GU
      - US-MI
      - US-MN
      - US-MP
      - US-PR
      - US-VI
      - US-MS

state:
  games:
    api:
      host: https://games.api.lottery.com/
      uri: api/v2.0/games?region=

draw:
  result:
    uri: https://graffy.api.lottery.com/graphql